extends: cheminfo

env:
  browser: true
  node: true
  es6: true

parserOptions:
  sourceType: module

rules:
  import/no-cycle: off
  import/no-extraneous-dependencies: off

settings:
  import/core-modules: [test]
